Repository openvinotoolkit/model_server, pull requests merged in 2021-12, with the labels that each got.

#1048 Request deserialize/serialize/validation unit tests API 2.0
  src/binaryutils.cpp
  src/customnodesession.cpp
  src/deserialization.cpp
  src/deserialization.hpp
  src/precision.hpp
  src/predict_request_validation_utils.cpp
  src/serialization.cpp
  src/tensorinfo.cpp
  src/tensorinfo.hpp
  src/test/deserialization_tests.cpp
  src/test/get_model_metadata_response_test.cpp
  src/test/get_model_metadata_signature_test.cpp
  src/test/ovtestutils.hpp
  src/test/predict_validation_test.cpp
  src/test/prediction_service_test.cpp
  src/test/serialization_tests.cpp
Labels: OV API 2.0

#1052 Client library - added PyPi overview markdown and changed version to 0.2
  client/python/lib/Makefile
  client/python/lib/README.md
  client/python/lib/docs/make_grpc_client.md
  client/python/lib/docs/pypi_overview.md
  client/python/lib/setup.py
Labels: ovmsclient

#1051 Layout API 2.0
  Makefile
  src/modelinstance.cpp
  src/modelinstance.hpp
  src/predict_request_validation_utils.cpp
  src/serialization.cpp
  src/tensorinfo.cpp
  src/tensorinfo.hpp
  src/test/binaryutils_test.cpp
  src/test/custom_loader_test.cpp
  src/test/ovtestutils.hpp
  src/test/predict_validation_test.cpp
  src/test/prediction_service_test.cpp
  src/test/serialization_tests.cpp
Labels: OV API 2.0

#1057 Client library - change PyPi project description
  client/python/lib/docs/pypi_overview.md
Labels: ovmsclient

#1076 Sphinx docs update
  README.md
  client/python/samples/README.md
  deploy/README.md
  docs/accelerators.md
  docs/api_reference_guide.md
  docs/architecture.md
  docs/binary_input.md
  docs/camera_example.md
  docs/clients.md
  docs/custom_node_development.md
  docs/dag_scheduler.md
  docs/demos.md
  docs/docker_container.md
  docs/dynamic_bs_auto_reload.md
  docs/dynamic_bs_demultiplexer.md
  docs/dynamic_input.md
  docs/dynamic_shape_auto_reload.md
  docs/dynamic_shape_binary_inputs.md
  docs/dynamic_shape_custom_node.md
  docs/host.md
  docs/installations_kubernetes.md
  docs/model_server_grpc_api.md
  docs/model_server_rest_api.md
  docs/model_version_policy.md
  docs/models_repository.md
  docs/multiple_models_mode.md
  docs/online_config_changes.md
  docs/parameters.md
  docs/performance_tuning.md
  docs/security_considerations.md
  docs/single_model_mode.md
  docs/starting_server.md
  docs/stateful_models.md
  docs/using_cloud_storage.md
  example_client/cpp/README.md
  example_client/go/README.md
  extras/nginx-mtls-auth/README.md
  extras/openvino-operator-openshift/README.md
  extras/ovms-operator/README.md
Labels: documentation

#1071 CVS-73561 Batch size 2.0 implementation & layout setting changes
  Dockerfile.centos
  Dockerfile.redhat
  Dockerfile.ubuntu
  Makefile
  src/BUILD
  src/dlnodesession.cpp
  src/layout.cpp
  src/layout.hpp
  src/modelconfig.cpp
  src/modelconfig.hpp
  src/modelinstance.cpp
  src/modelinstance.hpp
  src/modelmanager.cpp
  src/node.hpp
  src/node_library_utils.hpp
  src/predict_request_validation_utils.hpp
  src/prediction_service_utils.cpp
  src/prediction_service_utils.hpp
  src/shape.cpp
  src/shape.hpp
  src/status.cpp
  src/status.hpp
  src/tensorinfo.cpp
  src/tensorinfo.hpp
  src/test/custom_node_output_allocator_test.cpp
  src/test/ensemble_flow_custom_node_tests.cpp
  src/test/ensemble_tests.cpp
  src/test/model_cache_test.cpp
  src/test/modelconfig_test.cpp
  src/test/modelinstance_test.cpp
  src/test/modelmanager_test.cpp
  src/test/prediction_service_test.cpp
Labels: OV API 2.0

#1061 Support for dynamic shapes, batch size and new layout change
  Dockerfile.centos
  Dockerfile.redhat
  Dockerfile.ubuntu
  Makefile
  src/BUILD
  src/binaryutils.cpp
  src/custom_nodes/model_zoo_intel_object_detection/config_vehicles_example.json
  src/dlnodesession.cpp
  src/get_model_metadata_impl.cpp
  src/layout.cpp
  src/layout.hpp
  src/modelconfig.cpp
  src/modelconfig.hpp
  src/modelinstance.cpp
  src/modelinstance.hpp
  src/modelmanager.cpp
  src/node.hpp
  src/node_library_utils.cpp
  src/node_library_utils.hpp
  src/ov_utils.cpp
  src/pipelinedefinition.cpp
  src/pipelinedefinition.hpp
  src/predict_request_validation_utils.cpp
  src/predict_request_validation_utils.hpp
  src/prediction_service_utils.cpp
  src/prediction_service_utils.hpp
  src/serialization.cpp
  src/shape.cpp
  src/shape.hpp
  src/statefulmodelinstance.cpp
  src/status.cpp
  src/status.hpp
  src/tensorinfo.cpp
  src/tensorinfo.hpp
  src/test/binaryutils_test.cpp
  src/test/custom_node_output_allocator_test.cpp
  src/test/ensemble_flow_custom_node_tests.cpp
  src/test/ensemble_metadata_test.cpp
  src/test/ensemble_tests.cpp
  src/test/model_cache_test.cpp
  src/test/modelconfig_test.cpp
  src/test/modelinstance_test.cpp
  src/test/modelmanager_test.cpp
  src/test/prediction_service_test.cpp
  src/test/shape_test.cpp
  src/test/test_utils.cpp
Labels: OV API 2.0
