Repository openvinotoolkit/model_server, pull requests merged in 2022-08, with the labels that each got.

#1333 Add all ready versions into ModelMetadataResponse
  src/kfs_grpc_inference_service.cpp
  src/kfs_grpc_inference_service.hpp
  src/modelversionstatus.cpp
  src/modelversionstatus.hpp
  src/test/ensemble_mapping_config_tests.cpp
  src/test/kfs_metadata_test.cpp
  src/test/mockmodelinstancechangingstates.hpp
Labels: 2022.2

#1346 Change numpy version limitations
  client/python/ovmsclient/lib/setup.py
Labels: ovmsclient

#1341 Cvs 88692 benchmark client update
  demos/benchmark/python/Dockerfile
  demos/benchmark/python/README.md
  demos/benchmark/python/client.py
  demos/benchmark/python/client_kfs.py
  demos/benchmark/python/client_tfs.py
  demos/benchmark/python/db_exporter.py
  demos/benchmark/python/entrypoint.sh
  demos/benchmark/python/example_metadata.yml
  demos/benchmark/python/main.py
  demos/benchmark/python/metrics.py
  demos/benchmark/python/readme-img-urandom.png
  demos/benchmark/python/readme-img-xrandom.png
Labels: enhancement
