Repository openvinotoolkit/model_server, pull requests merged in 2023-09, with the labels that each got.

#2001 Add support for 0-dim requests via REST + more scalar tests
  src/rest_parser.cpp
  src/rest_utils.cpp
  src/status.cpp
  src/status.hpp
  src/test/ensemble_flow_custom_node_tests.cpp
  src/test/kfs_rest_parser_test.cpp
  src/test/kfs_rest_test.cpp
  src/test/prediction_service_test.cpp
  src/test/rest_utils_test.cpp
  src/test/tfs_rest_parser_column_test.cpp
  src/test/tfs_rest_parser_nonamed_test.cpp
  src/test/tfs_rest_parser_row_test.cpp
Labels: 2023.1

#2014 Add note about using MUSE model with cache
  demos/universal-sentence-encoder/README.md
Labels: 2023.1

#1989 Introducing Python in model server build system
  .bazelrc
  BUILD.bazel
  Dockerfile.redhat
  Dockerfile.ubuntu
  Makefile
  WORKSPACE
  ci/lib_search.py
  src/BUILD
  src/server.cpp
  third_party/python/BUILD
  third_party/python/python_repo.bzl
Labels: WIP, 2023.2

#2033 Coverity version bump & triage
  ci/.gitignore
  ci/Dockerfile.coverity
  src/BUILD
  src/dags/custom_node.cpp
  src/dags/dl_node.cpp
  src/dags/exit_node.hpp
  src/dags/nodeinfo.hpp
  src/get_model_metadata_impl.cpp
  src/get_model_metadata_impl.hpp
  src/model_service.cpp
  src/model_service.hpp
  src/modelmanager.cpp
Labels: 2023.2
